### ISSUE TITLE
RTSP Usage.

### ISSUE THREAD

**Issue by davesenior9** [connervieira/Predator#9]
Hi there, how do i go about integrating an RTSP feed? Cant see much in the usage document about it.

Thanks :)

**Comment by connervieira** [comment]
Thanks for your interest in the project! Unfortunately, Predator isn't designed to integrate with RTSP streams (or other network camera protocols). Vanilla Predator (this repository) is intended to be a self-contained ALPR platform that runs primarily offline.

If you're interested in network-oriented ALPR, you might be interested in [Predator Fabric](https://v0lttech.com/predatorfabric.php). Predator Fabric is intended to run on an SBC (like a Raspberry Pi) and feed ALPR results to a remote service (typically self-hosted). Instead of a single server running ALPR on multiple network cameras, each individual camera using Predator Fabric runs ALPR locally, then sends the results off to a centralized target.

Predator is designed to be a platform to allow hobbyists to build customizable small-scale ALPR systems. As such, I try to avoid features that would encourage it's use in mass surveillance. For customers with more extensive needs (for example, businesses or individuals with large properties), I often do custom implementations to fit their needs.

RTSP is a highly requested feature, but I want to be careful with how I implement it. Additionally, doing so would require I purchase various cameras for testing, which is difficult to justify for a feature outside of the main scope of the project.

In any case, I hope you'll find Predator and Predator Fabric to be useful. If you'd like to discuss more personalized options, be sure to [get in contact](https://v0lttech.com/contact.php).
